-- sql/init.sql

-- Primero, crea las tablas si no existen.
-- Esto asegura que los INSERTs tengan dónde ir.

CREATE TABLE IF NOT EXISTS paises (
    id_pais BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS personas (
    id_persona BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    edad INTEGER,
    id_pais BIGINT NOT NULL,
    CONSTRAINT fk_pais FOREIGN KEY (id_pais) REFERENCES paises (id_pais)
);


-- Insertar países
-- Usamos ON CONFLICT DO NOTHING para evitar errores si los datos ya existen
INSERT INTO paises (id_pais, nombre) VALUES (1, 'Chile') ON CONFLICT (id_pais) DO NOTHING;
INSERT INTO paises (id_pais, nombre) VALUES (2, 'Argentina') ON CONFLICT (id_pais) DO NOTHING;
INSERT INTO paises (id_pais, nombre) VALUES (3, 'Perú') ON CONFLICT (id_pais) DO NOTHING;
INSERT INTO paises (id_pais, nombre) VALUES (4, 'Colombia') ON CONFLICT (id_pais) DO NOTHING;

-- Insertar personas (asegúrate de que los IDs de país existan)
INSERT INTO personas (id_persona, nombre, edad, id_pais) VALUES (101, 'Juan Perez', 30, 1) ON CONFLICT (id_persona) DO NOTHING;
INSERT INTO personas (id_persona, nombre, edad, id_pais) VALUES (102, 'Maria Gomez', 25, 2) ON CONFLICT (id_persona) DO NOTHING;
INSERT INTO personas (id_persona, nombre, edad, id_pais) VALUES (103, 'Carlos Ruiz', 40, 1) ON CONFLICT (id_persona) DO NOTHING;
